### PR TITLE
Add perl Net::LDAP packages for Mavis

### PR DESCRIPTION
**Pull request by mattymo**

### CODE REVIEW

**Comment by mattymo** [comment]
@lfkeitel Can you take a look at this?

**Comment by lfkeitel** [comment]
Thanks for the contribution.

**Comment by mattymo** [comment]
My pleasure! I look forward to the updated docker tag.

**Comment by lfkeitel** [comment]
It's already pushed. It's the same versioned tag as the last ones since I'm going by the version of the upstream software. Probably not the best but I works for now.

**Pull request merged**
